# Generated by Django 5.0.2 on 2024-03-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_photo',
            field=models.ImageField(upload_to='class_files/'),
        ),
    ]
