# Generated by Django 5.0.2 on 2024-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_class_user_class_creator_classmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
