# Generated by Django 5.0.2 on 2024-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_room_roommembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dropzone_file',
            field=models.ImageField(upload_to='dropzone_files/'),
        ),
    ]
