# Generated by Django 5.0.3 on 2024-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_plan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('to do', 'To do'), ('done', 'Done'), ('doing', 'Doing')], max_length=20),
        ),
    ]
