# Generated by Django 5.0.3 on 2024-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_plan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('to_do', 'To_do'), ('done', 'Done'), ('doing', 'Doing')], max_length=20),
        ),
    ]
