# Generated by Django 5.0.4 on 2024-04-27 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lections/images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='lections/files/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lections', to=settings.AUTH_USER_MODEL)),
                ('specific_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lections', to='main.class')),
            ],
        ),
    ]
